{% set version = "3.6.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pdftools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pdftools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pdftools/pdftools_{{ version }}.tar.gz
  sha256: 4529a7669baaadbfbbb328c8c75d34c86f51cab5071945ff9cedd8f633f421c4
  patches:
    - patches/0001-add-pthread.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-qpdf                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-qpdf
    - poppler                      # [not win]
    - libiconv                     # [win]
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-qpdf
    - poppler                      # [not win]

test:
  commands:
    - $R -e "library('pdftools')"           # [not win]
    - "\"%R%\" -e \"library('pdftools')\""  # [win]

about:
  home: https://ropensci.r-universe.dev/pdftools
  dev_url: https://github.com/ropensci/pdftools
  doc_url: https://docs.ropensci.org/pdftools/
  license: MIT
  license_file: LICENSE
  summary: Utilities based on 'libpoppler' for extracting text, fonts, attachments and  metadata from a PDF file. Also supports high quality rendering of PDF documents info PNG, JPEG, TIFF format, or into raw bitmap vectors for further processing in R.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
