{% set version = "3.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pdftools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pdftools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pdftools/pdftools_{{ version }}.tar.gz
  sha256: 2651283b68826ed8dc73f33b41ae268332e4759d5efa3d06e0a4b6eb85c3d4d1

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-qpdf
    - poppler
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-qpdf
    - poppler

test:
  commands:
    - $R -e "library('pdftools')"           # [not win]
    - "\"%R%\" -e \"library('pdftools')\""  # [win]

about:
  home: https://ropensci.org/blog/2016/03/01/pdftools-and-jeroen (blog) https://github.com/ropensci/pdftools#readme (devel) https://poppler.freedesktop.org (upstream)
  license: MIT
  license_file: LICENSE
  summary: Utilities based on 'libpoppler' for extracting text, fonts, attachments and  metadata from a PDF file. Also supports high quality rendering of PDF documents info PNG, JPEG, TIFF format, or into raw bitmap vectors for further processing in R.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pdftools
# Type: Package
# Title: Text Extraction, Rendering and Converting of PDF Documents
# Version: 2.0
# Authors@R: person("Jeroen", "Ooms", role = c("aut", "cre"), email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289"))
# Description: Utilities based on 'libpoppler' for extracting text, fonts, attachments and  metadata from a PDF file. Also supports high quality rendering of PDF documents info PNG, JPEG, TIFF format, or into raw bitmap vectors for further processing in R.
# License: MIT + file LICENSE
# URL: https://ropensci.org/blog/2016/03/01/pdftools-and-jeroen (blog) https://github.com/ropensci/pdftools#readme (devel) https://poppler.freedesktop.org (upstream)
# BugReports: https://github.com/ropensci/pdftools/issues
# SystemRequirements: Poppler C++ API: libpoppler-cpp-dev (deb) or poppler-cpp-devel (rpm). The unit tests also require the 'poppler-data' package (rpm/deb)
# Encoding: UTF-8
# Imports: Rcpp (>= 0.12.12)
# LinkingTo: Rcpp
# Suggests: jpeg, png, webp, testthat
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2018-12-11 13:53:47 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-12-11 14:30:02 UTC
