appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NniV20e+tvk0PL4gi5XZ+EVmlvy/E0biXOpWhkklSgzeCv+oFFZqf5YVaa4DlQb/FRVuBjJ64RBY3fcEOJeVu6U/WCMz92jDaKwSSyDHhrtH5MA431/EmSTc+VlioFkcAmKQiQNB9H0bkBuE633wswZQlN54pqfBqslgoxFPDPg+7nWskK5kM8IeuvsSE4scqtIV0MSY9w8/Yh7xpObeG5muQyAmWHfTeXzOVjt3S+cRPsh1U9KjKR1C17bruCUxiZYRr5JtM7kBrj13g2sMDSdn8KewQIAkb7hU/3s6M4293fDxDb86SPcNsP9yiVO1+55Z2zc/v+nWt00SHMt5lC/DJsw8SKwJxqkuRXOT0FRDB80XW3L4hsotmDcZQaCqwz57FJ2OOlAC0Anue2AvmmcFVFLI5Hb2hjqJec/Ausihnv3rT454amp654DUBUiiHUEe/kGfsKHO88Flprli4ws7HA0ioE3r2bxRfVP0La8VPBA/HLqcqWz7PFdiEARPPveYj1RaxOINwcEgaRyZlfGwHhRmjZMBwnK46PKIjDQUt3xdWtaVMwL57TxnpwJQZEsBkHKVy5vuxsI+ulVI7aqB2RlWQG7zvCNGMUF/33KLhiHFpEJoKzJptLV8eQABZksIaRFE5jj44E5AwS256aQUr2n0JZu3XKlwBOlcOb4=
